### ISSUE TITLE
Do not set component id on more than one element

### ISSUE THREAD

**Issue by epsitec** [epsitec-sa/electrum-arc#6]
If a component has an associated id (`<TextField id="xyz" />`), then the generated HTML
should associate the id only with the active element (i.e. the `<input>` element).
- In HTML5, an `id` attribute is unique and may not be set on more than one element.
- Projects such as Lydia expect to be able to find a DOM element by its `id` (to set the focus or change the selection in an input field).

@SpeedyBlupi can you please look into this?

**Comment by SpeedyBlupi** [comment]
Resolved into commit 59e39276253ab7b71dbde299f57d2c225000e284

**Comment by epsitec** [comment]
@SpeedyBlupi your fix does not work. Settings `{...this.props}` on the `<span>` includes all properties, even the `id` which was passed in from the parent.

Generally speaking, it is not a good design practice to forward the props to the underlying HTML component. You should forward only the properties which are expected to be set on your component.

**Comment by epsitec** [comment]
Leave a comment
